"""acc_run acc_run_balance v3

Revision ID: 13f5b6c542a2
Revises: 5788ac1325cd
Create Date: 2024-06-18 04:11:11.864524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f5b6c542a2'
down_revision = '5788ac1325cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acc_run_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acc_run', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acc_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('profit_n', sa.Float(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('error_cnt', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['account'], ['accounts.id'], name='fk_acc_run_account'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('acc_runs', schema=None) as batch_op:
        batch_op.create_index('idx_acc_date', ['account', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acc_runs', schema=None) as batch_op:
        batch_op.drop_index('idx_acc_date')

    op.drop_table('acc_runs')
    op.drop_table('acc_run_balance')
    # ### end Alembic commands ###
