"""no index for balance 2

Revision ID: 30f853b6e60b
Revises: ebef5a32955d
Create Date: 2024-06-18 02:17:51.431028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f853b6e60b'
down_revision = 'ebef5a32955d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acc_run_balance', schema=None) as batch_op:
        batch_op.drop_constraint('fk_acc_run_balance_acc_run', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acc_run_balance', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_acc_run_balance_acc_run', 'acc_runs', ['acc_run'], ['id'])

    # ### end Alembic commands ###
