"""instrument.base_config

Revision ID: 3c5957a093e2
Revises: d08b8f783bfe
Create Date: 2025-02-12 00:21:21.170981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c5957a093e2'
down_revision = 'd08b8f783bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_config',
                                      sa.String(length=256), server_default='', nullable=False))

    # ### end Alembic commands ###

    # Копируем данные из поля config в base_config
    op.execute(
        """
        UPDATE instruments
        SET base_config = config
        """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_column('base_config')

    # ### end Alembic commands ###
