"""instr upd_date and profit

Revision ID: 42614688b11f
Revises: 1b0f3326de28
Create Date: 2024-06-06 16:50:19.394262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42614688b11f'
down_revision = '1b0f3326de28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_profit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('expected_profit')

    # ### end Alembic commands ###
