"""add expected_profit to run

Revision ID: 4aedecfaed5a
Revises: c861005cd9a8
Create Date: 2024-08-27 17:52:24.166322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aedecfaed5a'
down_revision = 'c861005cd9a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_profit', sa.Float(), nullable=True))

    # ### end Alembic commands ###

    # # Заполнение данных в новом столбце expected_profit
    # runs = Run.query.all()
    # for run in runs:
    #     log = InstrumentLog.query.filter_by(
    #         instrument_id=run.instrument
    #     ).filter(
    #         InstrumentLog.updated_at <= run.date
    #     ).order_by(InstrumentLog.updated_at.desc()).first()
    #
    #     if log:
    #         run.expected_profit = log.expected_profit
    #     else:
    #         run.expected_profit = None
    #
    # db.session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_column('expected_profit')

    # ### end Alembic commands ###
