"""acc_run acc_run_balance

Revision ID: 5088fa1c1971
Revises: 5788ac1325cd
Create Date: 2024-06-17 19:21:47.290724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5088fa1c1971'
down_revision = '5788ac1325cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acc_run_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acc_run', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acc_run'], ['acc_runs.id'], name='fk_acc_run_balance_acc_run'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('acc_run_balance', schema=None) as batch_op:
        batch_op.create_index('idx_acc_run_balance_date_time', ['acc_run', 'datetime'], unique=False)

    with op.batch_alter_table('acc_runs', schema=None) as batch_op:
        batch_op.create_index('idx_acc_date', ['account', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acc_runs', schema=None) as batch_op:
        batch_op.drop_index('idx_acc_date')

    with op.batch_alter_table('acc_run_balance', schema=None) as batch_op:
        batch_op.drop_index('idx_acc_run_balance_date_time')

    op.drop_table('acc_run_balance')
    # ### end Alembic commands ###
