"""data for inst and run

Revision ID: 558936d53395
Revises: 42614688b11f
Create Date: 2024-06-14 01:58:26.242588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558936d53395'
down_revision = '42614688b11f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.Text(), nullable=True))

    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instrument_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_column('instrument_data')

    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_column('data')

    # ### end Alembic commands ###
