"""run counters

Revision ID: 63f91d73a3f9
Revises: cc0add88b472
Create Date: 2024-05-24 16:25:26.748647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f91d73a3f9'
down_revision = 'cc0add88b472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_cnt', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('operations_cnt', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_column('operations_cnt')
        batch_op.drop_column('error_cnt')

    # ### end Alembic commands ###
