"""accounts

Revision ID: 7459f5cd624f
Revises: 9cf01e0884bc
Create Date: 2024-06-14 23:35:00.693478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7459f5cd624f'
down_revision = '9cf01e0884bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    # ### end Alembic commands ###
