"""instruments_log

Revision ID: 9cf01e0884bc
Revises: 558936d53395
Create Date: 2024-06-14 22:03:22.266800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cf01e0884bc'
down_revision = '558936d53395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('config', sa.String(length=256), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('expected_profit', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instruments_log')
    # ### end Alembic commands ###
