"""Add Command model

Revision ID: b56b8b21adba
Revises: 13f5b6c542a2
Create Date: 2024-06-18 15:58:33.672224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b56b8b21adba'
down_revision = '13f5b6c542a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_type', sa.Integer(), nullable=False),
    sa.Column('com_type', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.create_index('idx_bot_run_status', ['bot_type', 'run_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_index('idx_bot_run_status')

    op.drop_table('commands')
    # ### end Alembic commands ###
