"""instr names and run dates

Revision ID: cc0add88b472
Revises: dced450d602a
Create Date: 2024-05-23 18:31:54.346978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc0add88b472'
down_revision = 'dced450d602a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.alter_column('ticker', new_column_name='name', type_=sa.String(100))
        batch_op.alter_column('server', new_column_name='account')

    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime()))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.alter_column('name', new_column_name='ticker', type_=sa.String(10))
        batch_op.alter_column('account', new_column_name='server')

    # ### end Alembic commands ###
