"""acc_balance_correction

Revision ID: d08b8f783bfe
Revises: 57dc1a1ce828
Create Date: 2025-02-11 00:04:54.888832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd08b8f783bfe'
down_revision = '57dc1a1ce828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance_correction', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('balance_correction')

    # ### end Alembic commands ###
