"""no index for balance

Revision ID: ebef5a32955d
Revises: 5088fa1c1971
Create Date: 2024-06-18 02:05:10.887318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebef5a32955d'
down_revision = '5088fa1c1971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acc_run_balance', schema=None) as batch_op:
        batch_op.drop_index('idx_acc_run_balance_date_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acc_run_balance', schema=None) as batch_op:
        batch_op.create_index('idx_acc_run_balance_date_time', ['acc_run', 'datetime'], unique=False)

    # ### end Alembic commands ###
