"""run candle data

Revision ID: ee3176143cbb
Revises: adb13a8085db
Create Date: 2024-06-20 00:08:22.742138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee3176143cbb'
down_revision = 'adb13a8085db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('open', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('close', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('high', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('low', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('profit_n', sa.Float(), nullable=True))
        batch_op.drop_column('candle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candle', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('low')
        batch_op.drop_column('high')
        batch_op.drop_column('close')
        batch_op.drop_column('open')
        batch_op.drop_column('profit_n')

    # ### end Alembic commands ###
