"""account_foreign

Revision ID: f2d094067281
Revises: 7459f5cd624f
Create Date: 2024-06-15 01:01:33.504884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d094067281'
down_revision = '7459f5cd624f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_instruments_account', 'accounts', ['account'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_instruments_account', type_='foreignkey')

    # ### end Alembic commands ###
